#!/bin/bash

# --- Configuration ---
# Array of presentation files
FILES=(
  "1_intro.txt"
  "2_discovery_problem.txt"
  "3_discovery_protocol.txt"
  "4_discovery_flow.txt"
  "5_client_structure.txt"
  "6a_ai_initial_attempts.txt"
  "6b_ai_successful_strategy.txt"
  "7_conclusion.txt"
)

# Log file generated beforehand
LOG_FILE="run_log.txt"
# Catalog file generated by the ruby script
CATALOG_FILE="scripts/besu_jar_catalog.txt"

# --- ANSI Colors and Formatting ---
BOLD=$(tput bold)
RESET=$(tput sgr0)
CYAN=$(tput setaf 6)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
RED=$(tput setaf 1)

# --- Helper Functions ---
print_header() {
  local index=$1
  local file_to_display=$2
  # Use printf for potentially better ANSI code handling in header
  printf "%s--- Step %s / %s ---%s\n" "$BOLD" "$((index + 1))" "$NUM_FILES" "$RESET"
  printf "%sFile: %s%s\n" "$CYAN" "$file_to_display" "$RESET"
  echo "---------------------------------"
}

print_footer() {
 echo "---------------------------------"
}

check_file() {
  local file_path=$1
  local file_description=$2
  if [ ! -f "$file_path" ]; then
    # Use printf for color here too
    printf "%sError: %s file '%s' not found.%s\n" "$RED" "$file_description" "$file_path" "$RESET"
    echo "Please ensure it exists before running the presentation."
    exit 1
  fi
}

# --- Pre-run Checks ---
check_file "$LOG_FILE" "Log"
check_file "$CATALOG_FILE" "JAR Catalog"
# Check presentation files exist
for f in "${FILES[@]}"; do
  check_file "$f" "Presentation text"
done
# Check source file exists
check_file "src/main/java/com/yourcompany/minimalclient/MinimalClient.java" "MinimalClient source"


# --- State ---
NUM_FILES=${#FILES[@]}
CURRENT_INDEX=0

# --- Display Function ---
display_step() {
  clear
  local index=$1
  local file_to_display="${FILES[$index]}"

  print_header $index $file_to_display

  # *** Use printf to interpret escape codes in the file content ***
  printf "%b\n" "$(cat "$file_to_display")"

  print_footer

  # Add specific actions for certain steps
  case $index in
    0) # Intro - Show run command reference
      printf "%s## Showing the client run command (for reference):%s\n" "$GREEN" "$RESET"
      echo "$ gr run --args=\"--advertised-ip ... --bootstrap-nodes ...\"" # Truncated command
      ;;
    3) # Discovery Flow - Show grep commands from log
      printf "%s## Mapping logs to the flow (from %s):%s\n" "$GREEN" "$LOG_FILE" "$RESET"
      printf "%s# 1. Client PING -> Bootstrap:%s\n" "$CYAN" "$RESET"
      grep --color=auto 'Sending PING to 0xd860a01f' "$LOG_FILE"
      printf "%s# 2. Bootstrap PONG -> Client:%s\n" "$CYAN" "$RESET"
      grep --color=auto 'Received PONG from 0xd860a01f' "$LOG_FILE"
      printf "%s# 3. Bootstrap PING -> Client (Implied by Client's PONG response below):%s\n" "$CYAN" "$RESET" # Label only
      printf "%s# 4. Client PONG -> Bootstrap:%s\n" "$CYAN" "$RESET" # Label
      grep --color=auto 'Responding PONG to PING from /18.138.108.67' "$LOG_FILE" # Show the client's response
      printf "%s# -> Bonding (Client perspective):%s\n" "$CYAN" "$RESET"
      grep --color=auto 'transitioned to BONDED' "$LOG_FILE"
      printf "%s# 5. Client FINDNODE -> Bootstrap:%s\n" "$CYAN" "$RESET"
      grep --color=auto 'Sending FINDNODE request to 0xd860a01f' "$LOG_FILE"
      printf "%s# 6. Bootstrap NEIGHBORS -> Client:%s\n" "$CYAN" "$RESET"
      grep --color=auto 'Received [0-9]\+ neighbors from 0xd860a01f' "$LOG_FILE" | head -n 1
      ;;
    4) # Client Structure
       : # No-op, action handled by the main printf above
      ;;
    6) # AI Usage (Successful Strategy) - Show catalog preview
       printf "%s## Preview of Generated JAR Catalog (from %s):%s\n" "$GREEN" "$CATALOG_FILE" "$RESET"
       head -n 15 "$CATALOG_FILE"
       echo "..."
       ;;
    7) # Conclusion - Show final log lines
      printf "%s## Final Result (from %s):%s\n" "$GREEN" "$LOG_FILE" "$RESET"
      grep --color=auto -A 10 "Final Peer States" "$LOG_FILE" | head -n 15
      echo "..."
      ;;
    *) # Default case for steps without specific actions
      : # No-op
      ;;
  esac

  echo # Add a blank line before the prompt
}

# --- Main Loop ---
while true; do
  display_step $CURRENT_INDEX

  # Prompt for user input (Updated - using echo -n -e)
  echo -n -e "${YELLOW}[${BOLD}n${RESET}${YELLOW}]ext/[${BOLD}p${RESET}${YELLOW}]revious/[${BOLD}1-${NUM_FILES}${RESET}${YELLOW}] Jump/[${BOLD}q${RESET}${YELLOW}]uit: ${RESET}"
  read ACTION

  # Default action is 'next' if Enter is pressed
  ACTION=${ACTION:-n}

  # Check if input is a number (potential jump)
  if [[ "$ACTION" =~ ^[0-9]+$ ]]; then
    TARGET_INDEX=$((ACTION - 1)) # Convert step number (1-based) to index (0-based)
    if [ $TARGET_INDEX -ge 0 ] && [ $TARGET_INDEX -lt $NUM_FILES ]; then
      # Valid jump target
      CURRENT_INDEX=$TARGET_INDEX
      continue # Skip the rest of the loop and display the new step
    else
      # Invalid jump target
      printf "%sInvalid step number: %s. Please enter a number between 1 and %s.%s\n" "$RED" "$ACTION" "$NUM_FILES" "$RESET"
      sleep 2
      continue # Re-display current step
    fi
  fi

  # Handle non-numeric commands
  case $ACTION in
    n|N) # Next
      if [ $CURRENT_INDEX -lt $((NUM_FILES - 1)) ]; then
        CURRENT_INDEX=$((CURRENT_INDEX + 1))
      else
        echo "Already at the last step."
        sleep 1
      fi
      ;;
    p|P) # Previous
      if [ $CURRENT_INDEX -gt 0 ]; then
        CURRENT_INDEX=$((CURRENT_INDEX - 1))
      else
        echo "Already at the first step."
        sleep 1
      fi
      ;;
    q|Q) # Quit
      clear
      echo "Exiting presentation."
      exit 0
      ;;
    *) # Invalid input (already handled numeric cases above)
      printf "%sInvalid command: %s%s\n" "$RED" "$ACTION" "$RESET"
      sleep 1
      ;;
  esac
done
